provider:
  name: sls-offline

service: sls-offline

functions:
  generateGreetings:
    handler: Handlers/Greeting.generate
    events:
      - http:
          path: greetings
          method: post
          cors: true
  generatePigLatin:
    handler: Handlers/PigLatin.generate
    events:
      - http:
          path: piglatins
          method: post
          cors: true

plugins:
  - serverless-offline
